name: Deploy with OIDC

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for OIDC
      contents: read     # Required to checkout the repo

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::171171308751:role/github-action  # Replace with your real role ARN
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: |
          cd Terraform/EKS
          terraform init  

      - name: Terraform Validate
        run: terraform validate
        working-directory: Terraform/EKS

      - name: Terraform Plan
        run: terraform plan 
        working-directory: Terraform/EKS

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Terraform/EKS  
