name: Multi-cloud Terraform Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for OIDC
      contents: read     # Required to checkout the repo

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::171171308751:role/github-action  # Replace with your real role ARN
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

    
      - name: Initialize Terraform
        run: |
          cd multi-cloud-terraform/aws
          terraform init \
            -backend-config="bucket=terraform-state-bucket23" \
            -backend-config="key=dev/aws/terraform.tfstate" \
            -backend-config="region=us-east-1"
          terraform plan -var-file="../envs/dev/aws/terraform.tfvars"
          terraform apply -auto-approve -var-file="../envs/dev/aws/terraform.tfvars"
          
       
       #   # terraform import module.s3_storage.aws_s3_bucket.old_bucket my-dev-s3-bucket-multicloud
      
